language: java

os:
  - linux

jdk:
  - openjdk8
  - oraclejdk8

services:
  - postgresql

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database nativejson;' -U postgres

script:
  - mvn install -Pci -B
